apiVersion: apps/v1
kind: Deployment
metadata:
  name: hihello
  labels:
    app: hihello
spec:
  selector:
    matchLabels:
      app: hihello
  replicas: 1
  template:
    metadata:
      labels:
        app: hihello
    spec:
      containers:
      - name: hihello
        image: hihello:latest
        imagePullPolicy: Never
        env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        ports:
        - containerPort: 60000
        resources:
            requests:
                cpu: "500m"
            limits:
                cpu: "1000m"
